spring.datasource.url=jdbc:mysql://acela.proxy.rlwy.net:16417/railway
spring.datasource.username=root
spring.datasource.password=ZSgnoCyvBwZLEDHEiBFtGLyWprmBCKoX

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false